site_name: Payment and SCA for OpenID
site_url: https://aptitude-consortium.github.io/payments-and-sca-for-openid/
repo_url: https://github.com/APTITUDE-Consortium/payments-and-sca-for-openid
theme:
  name: material
  
  palette:

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.footer
    - navigation.sections
  logo: assets/logo.png
extra:
  version:
    provider: mike
    alias: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/APTITUDE-Consortium/payments-and-sca-for-openid
copyright: 2026 Aptitude Consortium
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format