site_name: Payment and SCA for OpenID
site_url: https://aptitude-consortium.github.io/payments-and-sca-for-openid/
theme:
  name: material
  palette:
    primary: black
  features:
    - navigation.footer
    - navigation.sections
  logo: assets/logo.png
extra:
  version:
    provider: mike
    default: stable
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/APTITUDE-Consortium/payments-and-sca-for-openid
copyright: 2026 Aptitude Consortium
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format